"""
emailer.py — Market Monitor email delivery
Phase 3: Gmail SMTP_SSL (port 465) with App Password via env var.
Phase 3b: load_dotenv removed — GitHub Actions injects env vars natively from secrets.

Environment variables (set as GitHub Actions secrets):
    GMAIL_APP_PASSWORD   — 16-char Gmail App Password (no spaces)
    EMAIL_SENDER         — sending address (e.g. sender@example.com)
    EMAIL_RECIPIENTS     — comma-separated recipient list (e.g. a@example.com,b@example.com)

Phase 4f: the two real addresses previously used as examples here were redacted
to example.com placeholders. This repository is public, so a real address in a
docstring is harvestable — and one of the two was a third party's.
"""

import logging
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import now_report   # Phase 4f: report timezone, never the runner's clock

logger = logging.getLogger(__name__)

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465   # SMTP_SSL


def send_report(html_path: str, subject: str) -> bool:
    """
    Send the HTML report as an inline email via Gmail SMTP_SSL.

    Args:
        html_path: Absolute path to the HTML report file.
        subject:   Email subject line (generated by validator.email_subject()).

    Returns:
        True if sent successfully, False otherwise.
    """
    app_password = os.environ.get("GMAIL_APP_PASSWORD", "").strip()
    sender = os.environ.get("EMAIL_SENDER", "").strip()
    recipients_raw = os.environ.get("EMAIL_RECIPIENTS", "").strip()

    if not app_password:
        logger.error("GMAIL_APP_PASSWORD env var not set — cannot send email")
        return False
    if not sender:
        logger.error("EMAIL_SENDER env var not set — cannot send email")
        return False
    if not recipients_raw:
        logger.error("EMAIL_RECIPIENTS env var not set — cannot send email")
        return False

    recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]
    if not recipients:
        logger.error("No valid recipients after parsing EMAIL_RECIPIENTS")
        return False

    if not os.path.isfile(html_path):
        logger.error(f"Report file not found: {html_path}")
        return False

    with open(html_path, "r", encoding="utf-8") as f:
        html_body = f.read()

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)

    plain_text = (
        f"Market Monitor — {now_report().strftime('%d %b %Y')}\n\n"
        "Please view this email in an HTML-capable client.\n\n"
        f"Subject: {subject}"
    )
    msg.attach(MIMEText(plain_text, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        logger.info(f"Connecting to {SMTP_HOST}:{SMTP_PORT} (SMTP_SSL)...")
        with smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) as server:
            server.login(sender, app_password)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info(f"Email sent to {recipients} | Subject: {subject}")
        return True

    except smtplib.SMTPAuthenticationError:
        logger.error(
            "Gmail authentication failed. Check that:\n"
            "  1. GMAIL_APP_PASSWORD is the 16-char App Password (no spaces)\n"
            "  2. 2-Step Verification is enabled on the sending account\n"
            "  3. The App Password was generated for 'Mail' / 'Other'"
        )
        return False

    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending email: {e}")
        return False

    except OSError as e:
        logger.error(f"Network error sending email: {e}")
        return False
